In [1]:
import numpy as np

In [3]:
mat=np.array([[1,0,-1],[4,0,0],[0,2,-2]])
b=np.array([0,2,1])
x=np.linalg.solve(mat,b)
x

array([0.5, 1. , 0.5])

In [4]:
x*2

array([1., 2., 1.])

In [9]:
mat=np.array([[1,0,-2],[1,4,-4],[1,2,0],[0,1,-1]])
print(mat)
b=np.array([0,1,2,0])
m=np.linalg.lstsq(mat,b)
print(m[0]*2)

[[ 1  0 -2]
 [ 1  4 -4]
 [ 1  2  0]
 [ 0  1 -1]]
[2. 1. 1.]


/home/cencina-004/Escritorio/12345/lib/python3.6/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


In [25]:
mat=np.array([[1,0,0,-2,0,0],[1,0,0,0,0,-1],[4,4,4,-4,-12,-4],[0,1,0,0,-2,0],[0,1,1,-1,-3,-1],[0,0,2,0,0,0]])
print(mat)
c=np.array([0,0,1,0,0,2])
m=np.linalg.solve(mat,c)
print(m*4*2)

[[  1   0   0  -2   0   0]
 [  1   0   0   0   0  -1]
 [  4   4   4  -4 -12  -4]
 [  0   1   0   0  -2   0]
 [  0   1   1  -1  -3  -1]
 [  0   0   2   0   0   0]]
[ 2. 10.  8.  1.  5.  2.]


In [26]:
c

array([0, 0, 1, 0, 0, 2])

In [30]:
sum(mat[2]*m*8)/c[2]

8.0